#!/bin/bash
#-------------------------------------------------------
# Bash-script autogenerated by im4java
# at Tue Mar 07 00:21:21 CST 2017
#-------------------------------------------------------

mogrify \
  "output.jpg" -resize "1280x960" "${1}"  \
  "(" \
    "?dop?"  \
  ")" \
   +append "${2}" 

